# Generated by Django 5.2.17 on 2026-09-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("color", models.CharField(default="#0d6efd", max_length=7)),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ordine"),
                ),
            ],
            options={
                "ordering": ["position", "code"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="codice"),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, unique=True, verbose_name="numero"),
                ),
                ("category", models.CharField(blank=True, max_length=10)),
                ("origin_code", models.CharField(blank=True, max_length=20)),
                (
                    "tracked",
                    models.BooleanField(default=False, verbose_name="monitorato"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trains.station",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trains",
                        to="trains.line",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="trains.station",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TrainRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="trains.train",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "train__number"],
                "unique_together": {("train", "service_date")},
            },
        ),
        migrations.CreateModel(
            name="StopTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "sched_arr",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="arrivo programmato"
                    ),
                ),
                (
                    "sched_dep",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="partenza programmata"
                    ),
                ),
                (
                    "actual_arr",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="arrivo reale"
                    ),
                ),
                (
                    "actual_dep",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="partenza reale"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stop_times",
                        to="trains.station",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trains.trainrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "sequence"],
                "unique_together": {("run", "sequence")},
            },
        ),
    ]
