# Generated by Django 5.2.17 on 2026-09-29 16:57

from django.db import migrations, models


def mark_existing_as_demo(apps, schema_editor):
    """Prima di questa versione nel database c'erano solo dati del simulatore."""
    Train = apps.get_model("trains", "Train")
    Train.objects.filter(tracked=False).update(is_demo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("trains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="discovered_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="is_demo",
            field=models.BooleanField(default=False, verbose_name="dato demo"),
        ),
        migrations.AddField(
            model_name="train",
            name="run_ts",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_as_demo, migrations.RunPython.noop),
    ]
